version: '3.8'

services:
  backend:
    build:
      context: ./Backend-Sys
      dockerfile: Dockerfile
    volumes:
      - ./Backend-Sys:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=data_shield_db
      - POSTGRES_USER=data_shield
      - POSTGRES_PASSWORD=data_shield_pass
      - POSTGRES_HOST=localhost
    command: python /app/manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./FrontEnd-Sys
      dockerfile: Dockerfile
    volumes:
      - ./Frontend-Sys:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: data_shield_db
      POSTGRES_USER: data_shield
      POSTGRES_PASSWORD: data_shield_pass

volumes:
  postgres_data: