services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend-Sys:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  backend:
    build:
      context: ./Backend-Sys
      dockerfile: Dockerfile
    volumes:
      - ./Backend-Sys:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PGHOST: db
      PGUSER: data_shield
      PGPASSWORD: data_shield_pass
      PGDATABASE: data_shield_db
      PGPORT: 5432
      DJANGO_SETTINGS_MODULE: data_shield.settings
    command: python /app/manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: data_shield_db
      POSTGRES_USER: data_shield
      POSTGRES_PASSWORD: data_shield_pass
    ports:
      - "5432:5432"

volumes:
  postgres_data:


