# Generated by Django 4.2.16 on 2024-10-31 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProtectionRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the data protection regulation.', max_length=255)),
                ('jurisdiction', models.CharField(blank=True, help_text='Jurisdiction of the regulation.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the regulation.')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, help_text='The user who reported the incident.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='DPIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data_types', models.JSONField()),
                ('risks', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(help_text='The organization for which the DPIA is conducted.', on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DataProcessingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(help_text='Name of the data processing activity.', max_length=255)),
                ('purpose', models.TextField(help_text='Purpose of the data processing activity.')),
                ('data_categories', models.TextField(help_text='Categories of data being processed.')),
                ('data_subjects', models.TextField(help_text='Data subjects whose data is being processed.')),
                ('retention_period', models.CharField(help_text='Duration for which the data will be retained.', max_length=100)),
                ('security_measures', models.TextField(help_text='Security measures in place for the data processing activity.')),
                ('is_high_risk', models.BooleanField(default=False, help_text='Indicates if the processing activity is considered high risk.')),
                ('last_reviewed', models.DateField(auto_now=True, help_text='Date when the data processing activity was last reviewed.')),
                ('organization', models.ForeignKey(help_text='The organization conducting the data processing activity.', on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non-compliant', 'Non-Compliant')], help_text='The compliance status of the organization.', max_length=20)),
                ('last_checked_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last compliance check.')),
                ('data_protection_regulations', models.ForeignKey(blank=True, help_text='Related data protection regulations.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance_management.dataprotectionregulation')),
                ('organization', models.ForeignKey(help_text='The organization for which the compliance status is recorded.', on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the compliance document.', max_length=255)),
                ('document_type', models.CharField(help_text='Type of the compliance document.', max_length=100)),
                ('file', models.FileField(help_text='The uploaded compliance document file.', upload_to='compliance_documents/')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the document was uploaded.')),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date of the compliance document.', null=True)),
                ('organization', models.ForeignKey(help_text='The organization that uploaded the document.', on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
                ('uploaded_by', models.ForeignKey(help_text='The user who uploaded the document.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the report was generated.')),
                ('report_type', models.CharField(help_text='Type of the compliance report.', max_length=100)),
                ('filters', models.JSONField(help_text='Filters used during report generation.')),
                ('file', models.FileField(help_text='The generated report file.', upload_to='compliance_reports/')),
                ('organization', models.ForeignKey(help_text='The organization for which the report is generated.', on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'generated_at'], name='compliance__organiz_99361e_idx'), models.Index(fields=['report_type'], name='compliance__report__6e1e32_idx')],
            },
        ),
    ]
