# Generated by Django 4.2.16 on 2024-10-31 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export Data'), ('IMPORT', 'Import Data'), ('COMPLIANCE_CHECK', 'Compliance Check')], help_text='The action performed.', max_length=20)),
                ('action_description', models.TextField(help_text='Description of the action performed.')),
                ('affected_resource', models.CharField(help_text='The resource affected by the action.', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the action was logged.')),
                ('is_compliant', models.BooleanField(default=True, help_text='Indicates if the action was compliant.')),
                ('compliance_notes', models.TextField(blank=True, help_text='Notes regarding compliance.')),
                ('additional_data', models.JSONField(blank=True, help_text='Store additional data as JSON.', null=True)),
                ('organization', models.ForeignKey(help_text='The organization related to the action.', on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='audit_log_a_organiz_ea776c_idx'), models.Index(fields=['action', 'created_at'], name='audit_log_a_action_a31d18_idx')],
            },
        ),
    ]
