# Generated by Django 4.2.16 on 2024-10-17 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('non-compliant', 'Non-Compliant')], max_length=20)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataProtectionRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jurisdiction', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KenyaDPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('section_in_act', models.CharField(max_length=50)),
                ('key_points', models.TextField(blank=True)),
                ('data_protection_regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_backend_app.dataprotectionregulation')),
            ],
        ),
        migrations.CreateModel(
            name='Gdpr4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('gdpr_articles', models.TextField()),
                ('recitals', models.TextField()),
                ('data_protection_regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_backend_app.dataprotectionregulation')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceStatusTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_compliance_status', models.CharField(blank=True, max_length=20)),
                ('new_compliance_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('compliance_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_backend_app.compliancestatus')),
                ('data_protection_regulations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_backend_app.dataprotectionregulation')),
            ],
        ),
        migrations.AddField(
            model_name='compliancestatus',
            name='data_protection_regulations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_backend_app.dataprotectionregulation'),
        ),
        migrations.AddField(
            model_name='compliancestatus',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_backend_app.organization'),
        ),
    ]
