# Generated by Django 4.2.16 on 2024-10-31 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the policy.', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title.', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Description of the policy.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the policy was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the policy was last updated.')),
                ('is_active', models.BooleanField(default=False, help_text='Indicates if the policy is active.')),
                ('created_by', models.ForeignKey(help_text='User  who created the policy.', on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(help_text='Version number of the policy.')),
                ('document', models.FileField(help_text='Uploaded policy document.', upload_to='policy_versions/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the version was created.')),
                ('created_by', models.ForeignKey(help_text='User  who created the version.', on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='policy_management.policy')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_management.policy')),
            ],
        ),
    ]
