# Generated by Django 4.2.16 on 2024-10-31 01:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the organization.', max_length=255)),
                ('address', models.CharField(help_text='The address of the organization.', max_length=255)),
                ('contact_person', models.CharField(help_text='The name of the contact person.', max_length=255)),
                ('contact_email', models.CharField(help_text='The email address of the contact person.', max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('contact_number', models.CharField(help_text='The contact number of the organization.', max_length=20)),
                ('industry', models.CharField(help_text='The industry in which the organization operates.', max_length=255)),
                ('company_size', models.CharField(help_text='The size of the company.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the organization was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the organization was last updated.')),
                ('slug', models.SlugField(blank=True, help_text='Unique slug for the organization.', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='First name of the user.', max_length=255)),
                ('last_name', models.CharField(help_text='Last name of the user.', max_length=255)),
                ('email', models.EmailField(help_text='Unique email address of the user.', max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the user was last updated.')),
                ('slug', models.SlugField(blank=True, help_text='Unique slug for the user.', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the user is active.')),
                ('is_staff', models.BooleanField(default=False, help_text='Indicates if the user can log into the admin interface.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', to='auth.group')),
                ('organization', models.ForeignKey(help_text='The organization the user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='authentication.organization')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
