name: MyApp Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      uses: docker/compose-action@v2
      with:
        compose-file: docker-compose.yml

    - name: Build the Docker image
      run: |
        docker-compose build --no-cache --build-arg TAG=$(date +%s)
