name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: data-shield_solutions
      run: |
        docker-compose -f docker-compose.yml build --no-cache --build-arg TAG=$(date +%s)
